Implement AVL tree
mindxhub/dna-go pull request #17
Opened 2020-06-06 05:31 UTC by vietduc01100001

Closes: #16

2020-06-06 05:37 UTC, vietduc01100001 commented
I implemented AVL tree in a package called `avl` by writing Binary Search Tree first (package named `bst`), and then imported `bst` like this:

```go
import (
	"github.com/vietduc01100001/dna-go/bst"
)
```

But since I don't code on the `master` branch, `go get` can't download the package and the compiler don't know where the the package `bst` comes from.

How do I import `bst` in package `avl` in this situation? @thanks173

2020-06-07 03:55 UTC, thanks173 commented
> How do I import `bst` in package `avl` in this situation? @thanks173

First, just run `go get github.com/vietduc01100001/dna-go/bst`
Then go to your package folder in `$GOPATH/src/github.com/vietduc01100001/dna-go/` and checkout to your desired branch.

2020-06-07 04:09 UTC, thanks173 commented on avl/avl.go
> +func (n *TreeNode) ensureBalance(node *Node) {
what is this `node` and its struct?

2020-06-07 04:10 UTC, thanks173 requested changes
After the rotation, the tree root could be changed. How do you keep track of that?

Also, your bst implementation contains bug, leaving a duplicate node after deletion.

2020-06-07 04:38 UTC, thanks173 commented on bst/bst.go
> +		node.Left.Delete(value)
there isn't a node with `value` in the left subtree.

2020-06-07 04:38 UTC, thanks173 commented on bst/bst.go
> +		node.Right.Delete(value)
there isn't a node with `value` in the right subtree.

2020-06-07 07:40 UTC, vietduc01100001 commented
> First, just run `go get github.com/vietduc01100001/dna-go/bst`
> Then go to your package folder in `$GOPATH/src/github.com/vietduc01100001/dna-go/` and checkout to your desired branch.

But `bst` isn't in the `master` branch, and as I know, `go get` only gets from the `master` branch.

2020-06-07 07:51 UTC, thanks173 commented
> 
> But `bst` isn't in the `master` branch, and as I know, `go get` only gets from the `master` branch.

`go get` is a wrapper around `git clone`. `$GOPATH/src/github.com/vietduc01100001/dna-go/` is your project folder and you can checkout this folder to any branch you want. You also can (and should) use this location to code.

2020-06-07 08:54 UTC, vietduc01100001 commented
> `go get` is a wrapper around `git clone`. `$GOPATH/src/github.com/vietduc01100001/dna-go/` is your project folder and you can checkout this folder to any branch you want. You also can (and should) use this location to code.

2021-02-04 15:23 UTC, closed without merging