Update README
mindxhub/dna-go pull request #9
Opened 2020-05-27 10:27 UTC by vietduc01100001

- Add Go installation link
- Add run tests command

2020-05-27 10:41 UTC, trungducc requested changes

2020-05-27 10:41 UTC, trungducc commented on README.md
> +## Installing Go
`Installing Go` should be a section in `Requirements`. For example:

## Requirements

- Go [v1.0.0+](https://golang.org/doc/install)

2020-05-27 14:15 UTC, trungducc approved these changes

2020-05-28 03:50 UTC, thanks173 approved these changes

2020-05-28 04:50 UTC, merged